theme = "onedark"

[editor]
scrolloff = 5
mouse = true
middle-click-paste = true
line-number = "absolute"
cursorline = false
cursorcolumn = false
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 50
completion-trigger-len = 2
completion-replace = true
auto-info = true
# true-color = true
# undercurl = false
# rulers = [80, 100]
bufferline = "never"
color-modes = false
text-width = 80
workspace-lsp-roots = []
auto-pairs = true

[editor.statusline]
left = ["mode", "file-type", "spinner"]
center = ["file-modification-indicator", "file-name", "version-control"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding","file-line-ending"]
separator = "|"
mode.normal = "ğŸ“„"
mode.insert = "ğŸ“"
mode.select = "ğŸ”"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
# goto-reference-include-declaration = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = true
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-exclude = true
# max-depth = 4

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "Â·"
nbsp = "â½"
tab = "â†’"
newline = "â"
tabpad = "Â·"

[editor.indent-guides]
render = true
character = "â–"
skip-levels = 1

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal.space]
# Add comma to the end of the line
"," = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ','",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
# Add semicolumn to the end of the line
";" = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ';'",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]

[keys.normal.space.c]
r = ":config-reload"
o = ":config-open"
l = ":o ~/.config/helix/languages.toml"
i = ":indent-style 4"